export const CONNECTION_PERSISTENCE = Symbol('CONNECTION_PERSISTENCE');
export const CONNECTION_AUTHORIZATION = Symbol('CONNECTION_AUTHORIZATION');
export const CONNECTION_ENCRYPTION = Symbol('CONNECTION_ENCRYPTION');
export const CONNECTION_TELEMETRY = Symbol('CONNECTION_TELEMETRY');
