-- ADR063: additive historical metadata, never a current-graph certification.
-- Held-traffic cutover only; neither an old image nor a writer is enabled here.
CREATE TABLE app.curated_template_rollout (
  singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),
  import_enabled boolean NOT NULL DEFAULT false
);
INSERT INTO app.curated_template_rollout(singleton,import_enabled) VALUES(true,false);
ALTER TABLE app.curated_template_rollout OWNER TO {{owner_role}};
REVOKE ALL ON app.curated_template_rollout FROM PUBLIC,{{api_runtime_role}},
  {{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};
-- Only the immutable singleton supports SHARE, never selection administration.
GRANT SELECT,UPDATE(singleton) ON app.curated_template_rollout TO {{api_runtime_role}};

CREATE TABLE app.curated_template_descriptors (
  template_id text NOT NULL CHECK(template_id ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND octet_length(template_id) BETWEEN 1 AND 64),
  template_version integer NOT NULL CHECK(template_version>0),
  schema_version integer NOT NULL CHECK(schema_version=1),
  base_manifest text NOT NULL CHECK(octet_length(base_manifest) BETWEEN 1 AND 2097152 AND jsonb_typeof(base_manifest::jsonb)='object'),
  base_manifest_digest char(64) NOT NULL CHECK(base_manifest_digest ~ '^[0-9a-f]{64}$' AND base_manifest_digest=encode(sha256(convert_to('pertexo.workflow.portable.manifest.v1','UTF8')||decode('00','hex')||convert_to(base_manifest,'UTF8')),'hex')),
  setup_targets jsonb NOT NULL CHECK(jsonb_typeof(setup_targets)='array' AND jsonb_array_length(setup_targets)<=16),
  supported_profile text NOT NULL CHECK(supported_profile='validate_activation'),
  selection_enabled boolean NOT NULL DEFAULT true,
  PRIMARY KEY(template_id,template_version)
);
ALTER TABLE app.curated_template_descriptors OWNER TO {{owner_role}};
REVOKE ALL ON app.curated_template_descriptors FROM PUBLIC,{{api_runtime_role}},
  {{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};
GRANT SELECT ON app.curated_template_descriptors TO {{api_runtime_role}};

-- BEGIN GENERATED CURATED TEMPLATE DESCRIPTORS
-- Generated by infrastructure/checks/curated-template-descriptors.mjs; do not hand-edit.
-- Selection is installed enabled; the independent template writer gate remains off.
INSERT INTO app.curated_template_descriptors
  (template_id, template_version, schema_version, base_manifest, base_manifest_digest, setup_targets, supported_profile, selection_enabled)
VALUES
  ($curated$controlled-http-notification$curated$, 1, 1, $curated${"connectionSlots":[{"authType":"http_headers","nodeId":"controlled-http","providerKey":"http","slot":"http_headers"},{"authType":"slack_bot_token","nodeId":"slack-notification","providerKey":"slack","slot":"slack_bot_token"}],"format":"pertexo.workflow","formatVersion":1,"graph":{"edges":[{"id":"notification-http","source":{"nodeId":"notification-start","port":"out"},"target":{"nodeId":"controlled-http","port":"in"}},{"id":"http-condition","source":{"nodeId":"controlled-http","port":"out"},"target":{"nodeId":"notify-on-200","port":"in"}},{"id":"condition-slack","source":{"nodeId":"notify-on-200","port":"true"},"target":{"nodeId":"slack-notification","port":"in"}},{"id":"slack-complete","source":{"nodeId":"slack-notification","port":"out"},"target":{"nodeId":"notification-complete","port":"in"}},{"id":"condition-skip","source":{"nodeId":"notify-on-200","port":"false"},"target":{"nodeId":"notification-skipped","port":"in"}}],"nodes":[{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.webhook","version":1},"id":"notification-start","inputMappings":{},"position":{"x":0,"y":0}},{"config":{"headers":{},"inlineResponseBytes":1024,"maxRedirects":0,"maxResponseBytes":1024,"method":"GET","timeoutMillis":1000,"url":"https://example.test/curated-demo"},"configVersion":1,"connectionRefs":{},"definition":{"key":"http.request","version":1},"id":"controlled-http","inputMappings":{},"position":{"x":0,"y":0}},{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.condition","version":1},"id":"notify-on-200","inputMappings":{"condition":{"expression":"nodeOutputs.\"controlled-http\".status = 200","kind":"expression","language":"jsonata","policyVersion":1}},"position":{"x":0,"y":0}},{"config":{"timeoutMillis":1000},"configVersion":1,"connectionRefs":{},"definition":{"key":"slack.send_message","version":1},"id":"slack-notification","inputMappings":{"channelId":{"kind":"literal","value":"CEXAMPLE"},"text":{"kind":"literal","value":"Curated demo: controlled endpoint returned 200."}},"position":{"x":0,"y":0}},{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.terminate","version":1},"id":"notification-complete","inputMappings":{"outcome":{"kind":"literal","value":"notification-complete"}},"position":{"x":0,"y":0}},{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.terminate","version":1},"id":"notification-skipped","inputMappings":{"outcome":{"kind":"literal","value":"notification-skipped"}},"position":{"x":0,"y":0}}],"schemaVersion":1,"settings":{"maxRunDurationMs":300000}},"requirements":{"definitions":[{"configVersion":1,"key":"core.condition","version":1},{"configVersion":1,"key":"core.terminate","version":1},{"configVersion":1,"key":"core.webhook","version":1},{"configVersion":1,"key":"http.request","version":1},{"configVersion":1,"key":"slack.send_message","version":1}],"selectionFingerprint":"node-select:v1:sha256:8d088833aecf943752bcd78cf18475e682cfae0b62f1b6445fb709fc4bd53513"}}$curated$::text, $curated$be2a8daaa8d220abf8be00c936df2cc3198cf8e64b88f0713baff8e3cebfdd46$curated$, $curated$[{"key":"url","location":"config","nodeId":"controlled-http","valueKind":"curated_https_endpoint_v1"},{"key":"channelId","location":"literalInput","nodeId":"slack-notification","valueKind":"slack_channel_id"}]$curated$::jsonb, $curated$validate_activation$curated$, TRUE),
  ($curated$schedule-bounded-batch$curated$, 1, 1, $curated${"connectionSlots":[],"format":"pertexo.workflow","formatVersion":1,"graph":{"edges":[{"id":"schedule-batch","source":{"nodeId":"schedule-start","port":"out"},"target":{"nodeId":"batch-items","port":"in"}},{"id":"batch-complete-edge","source":{"nodeId":"batch-items","port":"out"},"target":{"nodeId":"batch-complete","port":"in"}}],"nodes":[{"config":{"intervalMinutes":60,"kind":"interval","misfirePolicy":"skip"},"configVersion":3,"connectionRefs":{},"definition":{"key":"core.schedule","version":3},"id":"schedule-start","inputMappings":{},"position":{"x":0,"y":0}},{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.foreach","version":1},"id":"batch-items","inputMappings":{"items":{"kind":"literal","value":[{"value":"alpha"},{"value":"beta"}]}},"position":{"x":0,"y":0},"structured":{"body":{"edges":[],"inputPorts":["item","ordinal"],"nodes":[{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.set","version":1},"id":"batch-body-result","inputMappings":{"item":{"kind":"structured_input","path":"$","port":"item"},"ordinal":{"kind":"structured_input","path":"$","port":"ordinal"}},"position":{"x":0,"y":0}}],"outputPorts":["result"],"schemaVersion":1,"settings":{"maxRunDurationMs":300000}},"kind":"for_each","maxConcurrency":1,"maxIterations":3}},{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.terminate","version":1},"id":"batch-complete","inputMappings":{"result":{"kind":"node_output","nodeId":"batch-items","path":"$"}},"position":{"x":0,"y":0}}],"schemaVersion":1,"settings":{"maxRunDurationMs":300000}},"requirements":{"definitions":[{"configVersion":1,"key":"core.foreach","version":1},{"configVersion":3,"key":"core.schedule","version":3},{"configVersion":1,"key":"core.set","version":1},{"configVersion":1,"key":"core.terminate","version":1}],"selectionFingerprint":"node-select:v1:sha256:b6b636ddd0e5c092bd3020641f09cfc86dd9445fb9f8cc38328c9c2b25b7f7ad"}}$curated$::text, $curated$1ecab1f1b462fca2ad6542178952067eff50311e637caed1342d727fe2817a5d$curated$, $curated$[]$curated$::jsonb, $curated$validate_activation$curated$, TRUE),
  ($curated$webhook-validation-routing$curated$, 1, 1, $curated${"connectionSlots":[],"format":"pertexo.workflow","formatVersion":1,"graph":{"edges":[{"id":"start-validate","source":{"nodeId":"webhook-start","port":"out"},"target":{"nodeId":"validate-request","port":"in"}},{"id":"validate-route","source":{"nodeId":"validate-request","port":"out"},"target":{"nodeId":"route-validity","port":"in"}},{"id":"route-accepted","source":{"nodeId":"route-validity","port":"true"},"target":{"nodeId":"accepted","port":"in"}},{"id":"route-rejected","source":{"nodeId":"route-validity","port":"false"},"target":{"nodeId":"rejected","port":"in"}}],"nodes":[{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.webhook","version":1},"id":"webhook-start","inputMappings":{},"position":{"x":0,"y":0}},{"config":{"rules":[{"enum":["notification"],"id":"request-type","path":"$.payload.type","required":true,"type":"string"}]},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.validate","version":1},"id":"validate-request","inputMappings":{"payload":{"kind":"run_input","path":"$"}},"position":{"x":0,"y":0}},{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.condition","version":1},"id":"route-validity","inputMappings":{"condition":{"kind":"node_output","nodeId":"validate-request","path":"$.valid"}},"position":{"x":0,"y":0}},{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.terminate","version":1},"id":"accepted","inputMappings":{"outcome":{"kind":"literal","value":"accepted"}},"position":{"x":0,"y":0}},{"config":{},"configVersion":1,"connectionRefs":{},"definition":{"key":"core.terminate","version":1},"id":"rejected","inputMappings":{"outcome":{"kind":"literal","value":"rejected"}},"position":{"x":0,"y":0}}],"schemaVersion":1,"settings":{"maxRunDurationMs":300000}},"requirements":{"definitions":[{"configVersion":1,"key":"core.condition","version":1},{"configVersion":1,"key":"core.terminate","version":1},{"configVersion":1,"key":"core.validate","version":1},{"configVersion":1,"key":"core.webhook","version":1}],"selectionFingerprint":"node-select:v1:sha256:a0be3045940d79316109ba42ce12878987f59a13a5ee16c352a70948f5ba1090"}}$curated$::text, $curated$054903475c92270db247af785f4be6ba806e68023c167770cb9f767c77bb5239$curated$, $curated$[]$curated$::jsonb, $curated$validate_activation$curated$, TRUE);
-- END GENERATED CURATED TEMPLATE DESCRIPTORS

-- Installed content is immutable even for later owner selection changes.
CREATE FUNCTION app.guard_curated_template_descriptor() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $$
BEGIN
  IF TG_OP='DELETE' OR (to_jsonb(NEW)-'selection_enabled') IS DISTINCT FROM (to_jsonb(OLD)-'selection_enabled') THEN
    RAISE EXCEPTION 'curated descriptor content is immutable' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
ALTER FUNCTION app.guard_curated_template_descriptor() OWNER TO {{owner_role}};
REVOKE ALL ON FUNCTION app.guard_curated_template_descriptor() FROM PUBLIC;
CREATE TRIGGER curated_template_descriptor_immutable BEFORE UPDATE OR DELETE
  ON app.curated_template_descriptors FOR EACH ROW EXECUTE FUNCTION app.guard_curated_template_descriptor();

CREATE TABLE app.workflow_template_origins (
  workspace_id uuid NOT NULL, workflow_id uuid NOT NULL,
  origin jsonb NOT NULL CHECK(jsonb_typeof(origin)='object' AND octet_length(origin::text)<=512),
  PRIMARY KEY(workspace_id,workflow_id),
  FOREIGN KEY(workspace_id,workflow_id) REFERENCES app.workflows(workspace_id,id) ON DELETE CASCADE
);
ALTER TABLE app.workflow_template_origins OWNER TO {{owner_role}};
ALTER TABLE app.workflow_template_origins ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.workflow_template_origins FORCE ROW LEVEL SECURITY;
CREATE POLICY workflow_template_origins_tenant ON app.workflow_template_origins FOR SELECT TO {{api_runtime_role}}
  USING(workspace_id::text=nullif(current_setting('app.workspace_id',true),''));
CREATE POLICY workflow_template_origins_owner ON app.workflow_template_origins FOR ALL TO {{owner_role}}
  USING(true) WITH CHECK(true);
REVOKE ALL ON app.workflow_template_origins FROM PUBLIC,{{api_runtime_role}},
  {{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};
GRANT SELECT ON app.workflow_template_origins TO {{api_runtime_role}};

-- Readiness-only immutable inventory witness. No descriptor rows, selection
-- flags, tenant information, locks or caller-chosen relation escape this seam.
CREATE FUNCTION app.curated_template_inventory_matches(p_digest text)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path=pg_catalog,pg_temp SET row_security=on AS $$
DECLARE v_descriptor record; v_target jsonb; v_field text;
  v_target_text text; v_targets text; v_row text; v_inventory text:='';
BEGIN
  IF p_digest IS NULL OR p_digest COLLATE "C" !~ '^[0-9a-f]{64}$'
    OR octet_length(p_digest)<>64 THEN RETURN false; END IF;
  IF (SELECT count(*) FROM app.curated_template_descriptors) NOT BETWEEN 1 AND 128
    THEN RETURN false; END IF;
  FOR v_descriptor IN SELECT * FROM app.curated_template_descriptors
    ORDER BY template_id COLLATE "C",template_version
  LOOP
    IF jsonb_typeof(v_descriptor.setup_targets) IS DISTINCT FROM 'array'
      THEN RETURN false; END IF;
    IF jsonb_array_length(v_descriptor.setup_targets)>16 THEN RETURN false; END IF;
    v_targets:=jsonb_array_length(v_descriptor.setup_targets)::text||':';
    FOR v_target IN SELECT value FROM jsonb_array_elements(v_descriptor.setup_targets)
    LOOP
      IF jsonb_typeof(v_target) IS DISTINCT FROM 'object' THEN RETURN false; END IF;
      IF (SELECT array_agg(key ORDER BY key COLLATE "C") FROM jsonb_object_keys(v_target) key)
        IS DISTINCT FROM ARRAY['key','location','nodeId','valueKind']::text[]
        OR jsonb_typeof(v_target->'nodeId') IS DISTINCT FROM 'string'
        OR jsonb_typeof(v_target->'location') IS DISTINCT FROM 'string'
        OR jsonb_typeof(v_target->'key') IS DISTINCT FROM 'string'
        OR jsonb_typeof(v_target->'valueKind') IS DISTINCT FROM 'string'
        THEN RETURN false; END IF;
      v_target_text:='';
      FOREACH v_field IN ARRAY ARRAY[v_target->>'nodeId',v_target->>'location',
        v_target->>'key',v_target->>'valueKind'] LOOP
        v_target_text:=v_target_text||octet_length(v_field)::text||':'||v_field;
      END LOOP;
      v_targets:=v_targets||octet_length(v_target_text)::text||':'||v_target_text;
    END LOOP;
    v_row:='';
    FOREACH v_field IN ARRAY ARRAY[v_descriptor.template_id,v_descriptor.template_version::text,
      v_descriptor.schema_version::text,v_descriptor.base_manifest,v_descriptor.base_manifest_digest::text,
      v_targets,v_descriptor.supported_profile] LOOP
      v_row:=v_row||octet_length(v_field)::text||':'||v_field;
    END LOOP;
    v_inventory:=v_inventory||octet_length(v_row)::text||':'||v_row;
  END LOOP;
  RETURN encode(sha256(convert_to('pertexo.workflow.curated-inventory.v1','UTF8')
    ||decode('00','hex')||convert_to(v_inventory,'UTF8')),'hex')=p_digest;
END $$;
ALTER FUNCTION app.curated_template_inventory_matches(text) OWNER TO {{owner_role}};
REVOKE ALL ON FUNCTION app.curated_template_inventory_matches(text)
  FROM PUBLIC,{{api_runtime_role}},{{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};
GRANT EXECUTE ON FUNCTION app.curated_template_inventory_matches(text) TO {{api_runtime_role}},{{worker_runtime_role}};

-- API has no UPDATE privilege on descriptor content or selection. This confined
-- helper locks only one bounded identity; authority is checked before its lock.
CREATE FUNCTION app.lock_curated_template_descriptor(p_id text,p_version integer)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
SET search_path=pg_catalog,pg_temp SET row_security=on AS $$
DECLARE v_descriptor app.curated_template_descriptors%ROWTYPE;
  v_workspace uuid; v_actor uuid;
BEGIN
  IF p_id IS NULL OR octet_length(p_id) NOT BETWEEN 1 AND 64
    OR p_id !~ '^[a-z0-9]+(-[a-z0-9]+)*$' OR p_version IS NULL OR p_version<1 THEN
    RAISE EXCEPTION 'curated descriptor identity invalid' USING ERRCODE='22023';
  END IF;
  v_workspace:=nullif(current_setting('app.workspace_id',true),'')::uuid;
  v_actor:=nullif(current_setting('app.actor_id',true),'')::uuid;
  IF NOT EXISTS(SELECT 1 FROM app.workspaces WHERE id=v_workspace AND status='active')
    OR NOT EXISTS(SELECT 1 FROM app.users WHERE id=v_actor AND status='active')
    OR NOT EXISTS(SELECT 1 FROM app.workspace_memberships WHERE workspace_id=v_workspace
      AND user_id=v_actor AND status='active' AND role IN ('owner','admin','builder')) THEN
    RAISE EXCEPTION 'workflow author is not active' USING ERRCODE='42501';
  END IF;
  SELECT * INTO v_descriptor FROM app.curated_template_descriptors
    WHERE template_id=p_id AND template_version=p_version FOR SHARE;
  IF NOT FOUND THEN RETURN NULL; END IF;
  RETURN jsonb_build_object('schemaVersion',v_descriptor.schema_version,
    'templateId',v_descriptor.template_id,'templateVersion',v_descriptor.template_version,
    'baseManifestDigest',v_descriptor.base_manifest_digest,'manifest',v_descriptor.base_manifest::jsonb,
    'setupTargets',v_descriptor.setup_targets,'supportedProfile',v_descriptor.supported_profile,
    'selectionEnabled',v_descriptor.selection_enabled);
END $$;
ALTER FUNCTION app.lock_curated_template_descriptor(text,integer) OWNER TO {{owner_role}};
REVOKE ALL ON FUNCTION app.lock_curated_template_descriptor(text,integer)
  FROM PUBLIC,{{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};
GRANT EXECUTE ON FUNCTION app.lock_curated_template_descriptor(text,integer) TO {{api_runtime_role}};

-- No caller-provided verification bit: the creator verifies the immutable owner
-- descriptor and every typed delta itself, inside the locked claim transaction.
-- ADR063 curated_https_endpoint_v1: deliberately not a general URL parser.
-- Percent bytes remain opaque; only exact %2E is inspected for dot segments.
-- C collation makes each character class ASCII regardless of database locale.
CREATE FUNCTION app.curated_https_endpoint_valid(p_value text)
RETURNS boolean LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE
SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_remainder text; v_host text; v_path text; v_query text;
  v_labels text[]; v_label text; v_segment text; v_pairs text[]; v_pair text;
  v_name text; v_value text; v_separator integer;
BEGIN
  IF p_value IS NULL OR octet_length(p_value) NOT BETWEEN 1 AND 2048
    OR p_value COLLATE "C" !~ '^[!-~]+$'
    OR strpos(p_value,chr(92))>0 OR strpos(p_value,'#')>0 OR strpos(p_value,'@')>0
    OR left(p_value,8)<>'https://' THEN RETURN false; END IF;
  v_remainder:=substring(p_value FROM 9);
  v_separator:=strpos(v_remainder,'/');
  IF v_separator=0 THEN RETURN false; END IF;
  v_host:=left(v_remainder,v_separator-1);
  IF octet_length(v_host) NOT BETWEEN 1 AND 253 THEN RETURN false; END IF;
  v_labels:=string_to_array(v_host,'.');
  IF cardinality(v_labels)<2 THEN RETURN false; END IF;
  FOREACH v_label IN ARRAY v_labels LOOP
    IF octet_length(v_label) NOT BETWEEN 1 AND 63
      OR v_label COLLATE "C" !~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'
      OR left(v_label,4)='xn--' THEN RETURN false; END IF;
  END LOOP;
  IF v_labels[cardinality(v_labels)] COLLATE "C" !~ '^[a-z]{2,63}$'
    THEN RETURN false; END IF;
  v_path:=substring(v_remainder FROM v_separator);
  v_separator:=strpos(v_path,'?');
  IF v_separator>0 THEN
    v_query:=substring(v_path FROM v_separator+1);
    v_path:=left(v_path,v_separator-1);
  END IF;
  IF v_path COLLATE "C" !~ '^/([A-Za-z0-9._~/-]|%[0-9A-F]{2})*$'
    THEN RETURN false; END IF;
  FOREACH v_segment IN ARRAY string_to_array(v_path,'/') LOOP
    IF replace(v_segment,'%2E','.') IN ('.','..') THEN RETURN false; END IF;
  END LOOP;
  IF v_query IS NULL THEN RETURN true; END IF;
  IF v_query='' THEN RETURN false; END IF;
  v_pairs:=string_to_array(v_query,'&');
  IF cardinality(v_pairs) NOT BETWEEN 1 AND 16 THEN RETURN false; END IF;
  FOREACH v_pair IN ARRAY v_pairs LOOP
    v_separator:=strpos(v_pair,'=');
    IF v_separator=0 THEN RETURN false; END IF;
    v_name:=left(v_pair,v_separator-1);
    v_value:=substring(v_pair FROM v_separator+1);
    IF v_name COLLATE "C" !~ '^[A-Za-z0-9._~-]{1,64}$'
      OR v_name COLLATE "C" ~* 'auth|credential|secret|token|api[-_]?key'
      OR v_value COLLATE "C" !~ '^([A-Za-z0-9._~-]|%[0-9A-F]{2})*$'
      THEN RETURN false; END IF;
  END LOOP;
  RETURN true;
END $$;
ALTER FUNCTION app.curated_https_endpoint_valid(text) OWNER TO {{owner_role}};
REVOKE ALL ON FUNCTION app.curated_https_endpoint_valid(text)
  FROM PUBLIC,{{api_runtime_role}},{{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};

CREATE FUNCTION app.verify_curated_template_origin(p_manifest jsonb,p_origin jsonb,p_digest text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
SET search_path=pg_catalog,pg_temp SET row_security=on AS $$
DECLARE v_descriptor jsonb; v_comparison jsonb:=p_manifest; v_target jsonb;
  v_path text[]; v_matches integer; v_value jsonb; v_base jsonb; v_origin jsonb;
BEGIN
  IF jsonb_typeof(p_origin) IS DISTINCT FROM 'object' THEN
    RAISE EXCEPTION 'curated origin invalid' USING ERRCODE='42501';
  END IF;
  IF (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(p_origin) key)
      IS DISTINCT FROM ARRAY['baseManifestDigest','schemaVersion','templateId','templateVersion']::text[]
    OR p_origin->'schemaVersion' IS DISTINCT FROM '1'::jsonb
    OR jsonb_typeof(p_origin->'templateId') IS DISTINCT FROM 'string'
    OR octet_length(p_origin->>'templateId') NOT BETWEEN 1 AND 64
    OR p_origin->>'templateId' !~ '^[a-z0-9]+(-[a-z0-9]+)*$'
    OR jsonb_typeof(p_origin->'templateVersion') IS DISTINCT FROM 'number'
    OR p_origin->>'templateVersion' !~ '^[1-9][0-9]{0,9}$'
    OR (p_origin->>'templateVersion')::numeric>2147483647
    OR jsonb_typeof(p_origin->'baseManifestDigest') IS DISTINCT FROM 'string'
    OR p_origin->>'baseManifestDigest' !~ '^[0-9a-f]{64}$'
    OR p_digest IS NULL OR p_digest !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'curated origin invalid' USING ERRCODE='42501';
  END IF;
  v_descriptor:=app.lock_curated_template_descriptor(p_origin->>'templateId',(p_origin->>'templateVersion')::integer);
  IF v_descriptor IS NULL OR v_descriptor->'selectionEnabled' IS DISTINCT FROM 'true'::jsonb
    OR v_descriptor->'schemaVersion' IS DISTINCT FROM '1'::jsonb
    OR v_descriptor->'baseManifestDigest' IS DISTINCT FROM p_origin->'baseManifestDigest' THEN
    RAISE EXCEPTION 'curated descriptor unavailable' USING ERRCODE='42501';
  END IF;
  FOR v_target IN SELECT value FROM jsonb_array_elements(v_descriptor->'setupTargets')
  LOOP
    -- Traverse graph structure only. Never search similarly named literal data.
    WITH RECURSIVE graphs(graph,path,depth) AS (
      SELECT p_manifest->'graph',ARRAY['graph']::text[],0
      UNION ALL
      SELECT node.value->'structured'->'body',path||ARRAY['nodes',(node.ordinality-1)::text,'structured','body'],depth+1
      FROM graphs CROSS JOIN LATERAL jsonb_array_elements(
        CASE WHEN jsonb_typeof(graph->'nodes')='array' THEN graph->'nodes' ELSE '[]'::jsonb END
      ) WITH ORDINALITY node
      WHERE node.value->'structured'->>'kind'='for_each' AND depth<32
    ), targets AS (
      SELECT path||ARRAY['nodes',(node.ordinality-1)::text] path FROM graphs
      CROSS JOIN LATERAL jsonb_array_elements(
        CASE WHEN jsonb_typeof(graph->'nodes')='array' THEN graph->'nodes' ELSE '[]'::jsonb END
      ) WITH ORDINALITY node WHERE node.value->>'id'=v_target->>'nodeId'
    ) SELECT count(*),(SELECT path FROM targets LIMIT 1) INTO v_matches,v_path FROM targets;
    IF v_matches<>1 THEN RAISE EXCEPTION 'curated setup target invalid' USING ERRCODE='42501'; END IF;
    IF v_target->>'location'='config' THEN
      v_path:=v_path||ARRAY['config',v_target->>'key'];
    ELSIF v_target->>'location'='literalInput' THEN
      IF p_manifest#>(v_path||ARRAY['inputMappings',v_target->>'key','kind']) IS DISTINCT FROM '"literal"'::jsonb THEN
        RAISE EXCEPTION 'curated setup mapping invalid' USING ERRCODE='42501';
      END IF;
      v_path:=v_path||ARRAY['inputMappings',v_target->>'key','value'];
    ELSE RAISE EXCEPTION 'curated setup location invalid' USING ERRCODE='42501';
    END IF;
    v_value:=p_manifest#>v_path; v_base:=v_descriptor->'manifest'#>v_path;
    IF jsonb_typeof(v_value) IS DISTINCT FROM 'string' OR v_base IS NULL THEN
      RAISE EXCEPTION 'curated setup value invalid' USING ERRCODE='42501';
    END IF;
    IF v_target->>'valueKind'='slack_channel_id' THEN
      IF octet_length(v_value#>>'{}') NOT BETWEEN 2 AND 128 OR (v_value#>>'{}') !~ '^[CDGU][A-Z0-9]+$' THEN
        RAISE EXCEPTION 'curated setup value invalid' USING ERRCODE='42501';
      END IF;
    ELSIF v_target->>'valueKind'='curated_https_endpoint_v1' THEN
      IF NOT app.curated_https_endpoint_valid(v_value#>>'{}') THEN
        RAISE EXCEPTION 'curated setup value invalid' USING ERRCODE='42501';
      END IF;
    ELSE RAISE EXCEPTION 'curated setup kind invalid' USING ERRCODE='42501';
    END IF;
    v_comparison:=jsonb_set(v_comparison,v_path,v_base,false);
  END LOOP;
  IF v_comparison IS DISTINCT FROM v_descriptor->'manifest' THEN
    RAISE EXCEPTION 'curated manifest changed' USING ERRCODE='42501';
  END IF;
  v_origin:=p_origin||jsonb_build_object('creationCommandDigest',p_digest,'derivation','direct');
  IF octet_length(v_origin::text)>512 THEN RAISE EXCEPTION 'curated origin limit' USING ERRCODE='42501'; END IF;
  RETURN v_origin;
END $$;
ALTER FUNCTION app.verify_curated_template_origin(jsonb,jsonb,text) OWNER TO {{owner_role}};
REVOKE ALL ON FUNCTION app.verify_curated_template_origin(jsonb,jsonb,text)
  FROM PUBLIC,{{api_runtime_role}},{{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};

CREATE OR REPLACE FUNCTION app.create_workflow_import_draft(
  p_destination uuid,p_workspace uuid,p_actor uuid,p_graph jsonb,
  p_key_hash char,p_request_hash char,p_command text
) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER
SET search_path=pg_catalog,pg_temp SET row_security=on AS $$
DECLARE v_claim record; v_command jsonb; v_graph record; v_node record;
  v_nodes integer:=0; v_edges integer:=0;
  v_origin jsonb; v_expected_refs jsonb; v_connection record; v_workspace_status varchar;
BEGIN
  IF p_workspace::text IS DISTINCT FROM nullif(current_setting('app.workspace_id',true),'')
    OR p_actor::text IS DISTINCT FROM nullif(current_setting('app.actor_id',true),'') THEN
    RAISE EXCEPTION 'workflow context mismatch' USING ERRCODE='42501';
  END IF;
  -- Explicit lock order: workspace, actor, membership, claim, gate, catalog, connections.
  SELECT app.lock_workspace_run_admission(p_workspace) INTO v_workspace_status;
  IF v_workspace_status IS DISTINCT FROM 'active' THEN
    RAISE EXCEPTION 'workspace is not active' USING ERRCODE='42501';
  END IF;
  PERFORM 1 FROM app.users WHERE id=p_actor AND status='active' FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'actor is not active' USING ERRCODE='42501'; END IF;
  PERFORM 1 FROM app.workspace_memberships WHERE workspace_id=p_workspace AND user_id=p_actor
    AND status='active' AND role IN ('owner','admin','builder') FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'workflow author is not active' USING ERRCODE='42501'; END IF;
  SELECT request_hash,status,resource_id INTO v_claim FROM app.idempotency_records
    WHERE workspace_id=p_workspace AND operation='workflow.import'
      AND scope=p_actor::text AND key_hash=p_key_hash FOR UPDATE;
  IF NOT FOUND OR v_claim.status<>'in_progress' OR v_claim.resource_id<>p_destination
    OR v_claim.request_hash IS DISTINCT FROM p_request_hash THEN
    RAISE EXCEPTION 'workflow import claim mismatch' USING ERRCODE='42501';
  END IF;
  IF octet_length(p_command)>2097152 OR p_command IS NULL
    OR encode(sha256(convert_to(p_command,'UTF8')),'hex') IS DISTINCT FROM p_request_hash::text THEN
    RAISE EXCEPTION 'workflow import command mismatch' USING ERRCODE='42501';
  END IF;
  v_command:=p_command::jsonb;
  IF jsonb_typeof(v_command) IS DISTINCT FROM 'object'
    OR (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(v_command) key)
      NOT IN (ARRAY['bindings','expectedCompatibilityFingerprint','manifest','name']::text[],
        ARRAY['bindings','expectedCompatibilityFingerprint','manifest','name','templateOrigin']::text[])
    OR jsonb_typeof(v_command->'name') IS DISTINCT FROM 'string'
    OR jsonb_typeof(v_command->'expectedCompatibilityFingerprint') IS DISTINCT FROM 'string'
    OR jsonb_typeof(v_command->'manifest') IS DISTINCT FROM 'object'
    OR (SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(v_command->'manifest') key)
      IS DISTINCT FROM ARRAY['connectionSlots','format','formatVersion','graph','requirements']::text[]
    OR jsonb_typeof(v_command->'bindings') IS DISTINCT FROM 'array'
    OR jsonb_typeof(v_command->'manifest'->'connectionSlots') IS DISTINCT FROM 'array'
    OR jsonb_typeof(v_command->'manifest'->'requirements') IS DISTINCT FROM 'object'
    OR jsonb_typeof(v_command->'manifest'->'requirements'->'definitions') IS DISTINCT FROM 'array'
    OR jsonb_typeof(v_command->'manifest'->'requirements'->'selectionFingerprint') IS DISTINCT FROM 'string'
    OR jsonb_array_length(v_command->'manifest'->'requirements'->'definitions')>1000
    OR jsonb_array_length(v_command->'bindings')>1000
    OR jsonb_array_length(v_command->'manifest'->'connectionSlots')>1000 THEN
    RAISE EXCEPTION 'workflow import envelope invalid' USING ERRCODE='42501';
  END IF;
  IF v_command->>'name' IS NULL OR length(v_command->>'name') NOT BETWEEN 1 AND 128
    OR v_command->>'name'<>btrim(v_command->>'name')
    OR v_command->'manifest'->>'format' IS DISTINCT FROM 'pertexo.workflow'
    OR v_command->'manifest'->'formatVersion' IS DISTINCT FROM '1'::jsonb
    OR p_graph->'schemaVersion' IS DISTINCT FROM '1'::jsonb THEN
    RAISE EXCEPTION 'workflow import command invalid' USING ERRCODE='42501';
  END IF;
  PERFORM 1 FROM app.workflow_portability_rollout WHERE singleton AND import_enabled FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'workflow import is disabled' USING ERRCODE='55000'; END IF;
  IF v_command ? 'templateOrigin' THEN
    PERFORM 1 FROM app.curated_template_rollout WHERE singleton AND import_enabled FOR SHARE;
    IF NOT FOUND THEN RAISE EXCEPTION 'curated template import is disabled' USING ERRCODE='55000'; END IF;
    v_origin:=app.verify_curated_template_origin(v_command->'manifest',v_command->'templateOrigin',p_request_hash::text);
  END IF;
  PERFORM 1 FROM app.node_compatibility_current WHERE singleton
    AND fingerprint=v_command->>'expectedCompatibilityFingerprint' FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'workflow import catalog changed' USING ERRCODE='40001'; END IF;
  IF jsonb_typeof(v_command->'manifest'->'graph'->'nodes') IS DISTINCT FROM 'array'
    OR jsonb_typeof(p_graph->'nodes') IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'workflow import graph invalid' USING ERRCODE='42501';
  END IF;
  -- Compare graph pairs structurally, never traverse similarly named literal data.
  -- The only permitted transformation is replacing typed connectionRefs with the
  -- exact submitted bindings. The command text is ephemeral, not a receipt body.
  FOR v_graph IN
    WITH RECURSIVE graphs(source,destination,depth) AS (
      SELECT v_command->'manifest'->'graph',p_graph,0
      UNION ALL
      SELECT source_node.value->'structured'->'body',destination_node.value->'structured'->'body',depth+1
      FROM graphs
      CROSS JOIN LATERAL jsonb_array_elements(source->'nodes') WITH ORDINALITY source_node
      JOIN LATERAL jsonb_array_elements(destination->'nodes') WITH ORDINALITY destination_node
        ON destination_node.ordinality=source_node.ordinality
      WHERE source_node.value ? 'structured' AND depth<32
    ) SELECT * FROM graphs
  LOOP
    IF jsonb_typeof(v_graph.source) IS DISTINCT FROM 'object'
      OR jsonb_typeof(v_graph.destination) IS DISTINCT FROM 'object'
      OR v_graph.source->'schemaVersion' IS DISTINCT FROM '1'::jsonb
      OR jsonb_typeof(v_graph.source->'nodes') IS DISTINCT FROM 'array'
      OR jsonb_typeof(v_graph.destination->'nodes') IS DISTINCT FROM 'array'
      OR jsonb_typeof(v_graph.source->'edges') IS DISTINCT FROM 'array'
      OR jsonb_typeof(v_graph.source->'settings') IS DISTINCT FROM 'object' THEN
      RAISE EXCEPTION 'workflow import graph invalid' USING ERRCODE='42501';
    END IF;
    v_nodes:=v_nodes+jsonb_array_length(v_graph.source->'nodes');
    v_edges:=v_edges+jsonb_array_length(v_graph.source->'edges');
    IF v_nodes>1000 OR v_edges>4000 THEN
      RAISE EXCEPTION 'workflow import graph limit' USING ERRCODE='42501';
    END IF;
    IF v_graph.source-'nodes' IS DISTINCT FROM v_graph.destination-'nodes'
      OR jsonb_array_length(v_graph.source->'nodes')<>jsonb_array_length(v_graph.destination->'nodes') THEN
      RAISE EXCEPTION 'workflow import graph changed' USING ERRCODE='42501';
    END IF;
    FOR v_node IN SELECT source_node.value source,destination_node.value destination
      FROM jsonb_array_elements(v_graph.source->'nodes') WITH ORDINALITY source_node
      JOIN jsonb_array_elements(v_graph.destination->'nodes') WITH ORDINALITY destination_node
        ON destination_node.ordinality=source_node.ordinality
    LOOP
      IF jsonb_typeof(v_node.source) IS DISTINCT FROM 'object'
        OR jsonb_typeof(v_node.source->'id') IS DISTINCT FROM 'string'
        OR length(v_node.source->>'id')=0
        OR jsonb_typeof(v_node.source->'definition') IS DISTINCT FROM 'object'
        OR jsonb_typeof(v_node.source->'config') IS DISTINCT FROM 'object'
        OR jsonb_typeof(v_node.source->'inputMappings') IS DISTINCT FROM 'object'
        OR jsonb_typeof(v_node.destination->'connectionRefs') IS DISTINCT FROM 'object'
        OR jsonb_typeof(v_node.source->'position') IS DISTINCT FROM 'object' THEN
        RAISE EXCEPTION 'workflow import node invalid' USING ERRCODE='42501';
      END IF;
      IF v_node.source-'connectionRefs'-'structured' IS DISTINCT FROM v_node.destination-'connectionRefs'-'structured'
        OR (v_node.source->'structured')-'body' IS DISTINCT FROM (v_node.destination->'structured')-'body'
        OR v_node.source->'connectionRefs' IS DISTINCT FROM '{}'::jsonb
        OR (v_graph.depth=32 AND v_node.source ? 'structured') THEN
        RAISE EXCEPTION 'workflow import node changed' USING ERRCODE='42501';
      END IF;
      SELECT coalesce(jsonb_object_agg(binding->>'slot',binding->'connectionId'),'{}'::jsonb)
        INTO v_expected_refs FROM jsonb_array_elements(v_command->'bindings') binding
        WHERE binding->>'nodeId'=v_node.source->>'id';
      IF v_node.destination->'connectionRefs' IS DISTINCT FROM v_expected_refs THEN
        RAISE EXCEPTION 'workflow import binding changed' USING ERRCODE='42501';
      END IF;
    END LOOP;
  END LOOP;
  -- Slot declarations must match bindings exactly, including no duplicate/extra entries.
  IF jsonb_array_length(v_command->'bindings')<>jsonb_array_length(v_command->'manifest'->'connectionSlots')
    OR EXISTS(SELECT 1 FROM jsonb_array_elements(v_command->'bindings') b
      WHERE (SELECT count(*) FROM jsonb_array_elements(v_command->'bindings') d
        WHERE d->>'nodeId'=b->>'nodeId' AND d->>'slot'=b->>'slot')<>1
      OR (SELECT count(*) FROM jsonb_array_elements(v_command->'manifest'->'connectionSlots') s
        WHERE s->>'nodeId'=b->>'nodeId' AND s->>'slot'=b->>'slot')<>1) THEN
    RAISE EXCEPTION 'workflow import slots changed' USING ERRCODE='42501';
  END IF;
  FOR v_connection IN SELECT b->>'connectionId' id,s->>'providerKey' provider,s->>'authType' auth
    FROM jsonb_array_elements(v_command->'bindings') b
    JOIN jsonb_array_elements(v_command->'manifest'->'connectionSlots') s
      ON s->>'nodeId'=b->>'nodeId' AND s->>'slot'=b->>'slot'
    ORDER BY b->>'connectionId',b->>'nodeId',b->>'slot'
  LOOP
    PERFORM 1 FROM app.connections WHERE workspace_id=p_workspace AND id=v_connection.id::uuid
      AND provider_key=v_connection.provider AND auth_type=v_connection.auth AND status='active' FOR SHARE;
    IF NOT FOUND THEN RAISE EXCEPTION 'workflow connection is not available' USING ERRCODE='42501'; END IF;
  END LOOP;
  INSERT INTO app.workflows(id,workspace_id,name,lifecycle_status,activation_status,created_by)
    VALUES(p_destination,p_workspace,v_command->>'name','active','inactive',p_actor);
  INSERT INTO app.workflow_drafts(workflow_id,workspace_id,revision,schema_version,graph_json,updated_by)
    VALUES(p_destination,p_workspace,1,1,p_graph,p_actor);
  IF v_origin IS NOT NULL THEN
    INSERT INTO app.workflow_template_origins(workspace_id,workflow_id,origin)
      VALUES(p_workspace,p_destination,v_origin);
  END IF;
  RETURN p_destination;
END $$;
ALTER FUNCTION app.create_workflow_import_draft(uuid,uuid,uuid,jsonb,char,char,text) OWNER TO {{owner_role}};
REVOKE ALL ON FUNCTION app.create_workflow_import_draft(uuid,uuid,uuid,jsonb,char,char,text)
  FROM PUBLIC,{{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};
GRANT EXECUTE ON FUNCTION app.create_workflow_import_draft(uuid,uuid,uuid,jsonb,char,char,text) TO {{api_runtime_role}};

CREATE OR REPLACE FUNCTION app.create_workflow_duplicate_draft(
  p_destination uuid, p_workspace uuid, p_source uuid, p_actor uuid,
  p_name varchar, p_schema integer, p_graph jsonb,
  p_key_hash char, p_request_hash char, p_kind text, p_version uuid
) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER
SET search_path=pg_catalog,pg_temp SET row_security=on AS $$
DECLARE v_source_graph jsonb; v_claim record; v_reference record;
BEGIN
  IF p_workspace::text IS DISTINCT FROM nullif(current_setting('app.workspace_id',true),'')
    OR p_actor::text IS DISTINCT FROM nullif(current_setting('app.actor_id',true),'') THEN
    RAISE EXCEPTION 'workflow context mismatch' USING ERRCODE='42501';
  END IF;
  PERFORM 1 FROM app.workspace_memberships membership
    JOIN app.users actor ON actor.id=membership.user_id
    JOIN app.workspaces workspace ON workspace.id=membership.workspace_id
    WHERE membership.workspace_id=p_workspace AND membership.user_id=p_actor
      AND membership.status='active' AND membership.role IN ('owner','admin','builder')
      AND actor.status='active' AND workspace.status='active'
    FOR SHARE OF membership,actor,workspace;
  IF NOT FOUND THEN RAISE EXCEPTION 'workflow author is not active' USING ERRCODE='42501'; END IF;
  PERFORM 1 FROM app.workflows WHERE workspace_id=p_workspace AND id=p_source
    AND lifecycle_status='active' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'workflow source is not visible' USING ERRCODE='42501'; END IF;
  SELECT request_hash,status,resource_id INTO v_claim FROM app.idempotency_records
    WHERE workspace_id=p_workspace AND operation='workflow.duplicate'
      AND scope=p_actor::text||':'||p_source::text AND key_hash=p_key_hash FOR UPDATE;
  IF NOT FOUND OR v_claim.status<>'in_progress' OR v_claim.resource_id<>p_destination
    OR v_claim.request_hash IS DISTINCT FROM p_request_hash THEN
    RAISE EXCEPTION 'workflow duplication claim mismatch' USING ERRCODE='42501';
  END IF;
  IF p_kind='draft' AND p_version IS NULL THEN
    SELECT graph_json INTO v_source_graph FROM app.workflow_drafts
      WHERE workspace_id=p_workspace AND workflow_id=p_source FOR UPDATE;
  ELSIF p_kind='version' AND p_version IS NOT NULL THEN
    SELECT graph_json INTO v_source_graph FROM app.workflow_versions
      WHERE workspace_id=p_workspace AND workflow_id=p_source AND id=p_version FOR SHARE;
  ELSE RAISE EXCEPTION 'workflow source selector invalid' USING ERRCODE='22023';
  END IF;
  IF v_source_graph IS NULL OR v_source_graph IS DISTINCT FROM p_graph OR p_schema<>1
    OR p_destination=p_source OR p_name IS NULL OR length(btrim(p_name)) NOT BETWEEN 1 AND 128 THEN
    RAISE EXCEPTION 'workflow source content mismatch' USING ERRCODE='42501';
  END IF;
  -- Traverse only structured graph bodies, never similarly named user literals.
  FOR v_reference IN
    WITH RECURSIVE graphs(graph) AS (
      SELECT v_source_graph UNION ALL
      SELECT node.value->'structured'->'body' FROM graphs
        CROSS JOIN LATERAL jsonb_array_elements(graph->'nodes') node
        WHERE node.value->'structured'->>'kind'='for_each'
    ) SELECT DISTINCT reference.value::uuid AS id FROM graphs
      CROSS JOIN LATERAL jsonb_array_elements(graph->'nodes') node
      CROSS JOIN LATERAL jsonb_each_text(node.value->'connectionRefs') reference
      ORDER BY id
  LOOP
    PERFORM 1 FROM app.connections WHERE workspace_id=p_workspace AND id=v_reference.id FOR KEY SHARE;
    IF NOT FOUND THEN RAISE EXCEPTION 'workflow connection is not visible' USING ERRCODE='42501'; END IF;
  END LOOP;
  INSERT INTO app.workflows(id,workspace_id,name,lifecycle_status,activation_status,created_by)
    VALUES(p_destination,p_workspace,p_name,'active','inactive',p_actor);
  INSERT INTO app.workflow_drafts(workflow_id,workspace_id,revision,schema_version,graph_json,updated_by)
    VALUES(p_destination,p_workspace,1,p_schema,v_source_graph,p_actor);
  -- Source workflow lock fences edits/purge; origin is immutable and inherited
  -- without any current writer gate, descriptor or graph-equivalence lookup.
  INSERT INTO app.workflow_template_origins(workspace_id,workflow_id,origin)
    SELECT p_workspace,p_destination,origin||jsonb_build_object('derivation','inherited')
      FROM app.workflow_template_origins WHERE workspace_id=p_workspace AND workflow_id=p_source;
  RETURN p_destination;
END $$;
ALTER FUNCTION app.create_workflow_duplicate_draft(uuid,uuid,uuid,uuid,varchar,integer,jsonb,char,char,text,uuid)
  OWNER TO {{owner_role}};
REVOKE ALL ON FUNCTION app.create_workflow_duplicate_draft(uuid,uuid,uuid,uuid,varchar,integer,jsonb,char,char,text,uuid)
  FROM PUBLIC,{{worker_runtime_role}},{{dispatcher_role}},{{maintenance_role}},{{operator_role}},{{lifecycle_command_role}};
GRANT EXECUTE ON FUNCTION app.create_workflow_duplicate_draft(uuid,uuid,uuid,uuid,varchar,integer,jsonb,char,char,text,uuid)
  TO {{api_runtime_role}};
