import {
  artifactMetadataResponseSchema,
  nodeDefinitionListResponseSchema,
  connectionListResponseSchema,
  apiProblemSchema,
  accessibleWorkspacesResponseSchema,
  nodeValidationResponseSchema,
  failureNotificationDestinationListResponseSchema,
  scheduleTriggerListResponseSchema,
  workflowListResponseSchema,
  workflowPortableManifestSchema,
  workflowImportPreviewResponseSchema,
  parsePortableJson,
  portableGraphDigest,
  workflowRunResponseSchema,
  webhookTriggerListResponseSchema,
  workspaceInboxListResponseSchema,
} from '@pertexo/contracts';

export const browserContractConsumer = Object.freeze({
  artifact: artifactMetadataResponseSchema,
  connections: connectionListResponseSchema,
  failureNotifications: failureNotificationDestinationListResponseSchema,
  nodeDefinitions: nodeDefinitionListResponseSchema,
  nodeValidation: nodeValidationResponseSchema,
  problem: apiProblemSchema,
  schedules: scheduleTriggerListResponseSchema,
  workspaces: accessibleWorkspacesResponseSchema,
  workflows: workflowListResponseSchema,
  workflowRun: workflowRunResponseSchema,
  workflowPortable: workflowPortableManifestSchema,
  workflowPortablePreview: workflowImportPreviewResponseSchema,
  parsePortableJson,
  portableGraphDigest,
  webhooks: webhookTriggerListResponseSchema,
  workspaceInbox: workspaceInboxListResponseSchema,
});
