receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
  resource/drop_process_identity:
    attributes:
      - action: delete
        key: process.pid
      - action: delete
        key: process.parent_pid
      - action: delete
        key: process.command
      - action: delete
        key: process.command_args
      - action: delete
        key: process.executable.name
      - action: delete
        key: process.executable.path
      - action: delete
        key: process.owner
      - action: delete
        key: host.id
      - action: delete
        key: host.name
      - action: delete
        key: service.instance.id

exporters:
  debug:
    verbosity: basic
  prometheus:
    endpoint: 0.0.0.0:9464
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource/drop_process_identity, batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource/drop_process_identity, batch]
      exporters: [debug]
  telemetry:
    logs:
      level: info
