export const WORKFLOW_AUTHORING_PERSISTENCE = Symbol(
  'WORKFLOW_AUTHORING_PERSISTENCE',
);
export const WORKFLOW_AUTHORING_AUTHORIZATION = Symbol(
  'WORKFLOW_AUTHORING_AUTHORIZATION',
);
export const WORKFLOW_AUTHORING_TELEMETRY = Symbol(
  'WORKFLOW_AUTHORING_TELEMETRY',
);
export const WORKFLOW_DEFINITION_CATALOG = Symbol(
  'WORKFLOW_DEFINITION_CATALOG',
);
