export const IDENTITY_WORKSPACE_CONFIG = Symbol('IDENTITY_WORKSPACE_CONFIG');
export const IDENTITY_CRYPTO = Symbol('IDENTITY_CRYPTO');
export const IDENTITY_CLOCK = Symbol('IDENTITY_CLOCK');
export const OIDC_PROVIDER = Symbol('OIDC_PROVIDER');
export const OIDC_TRANSACTIONS = Symbol('OIDC_TRANSACTIONS');
export const IDENTITY_WORKSPACE_PERSISTENCE = Symbol(
  'IDENTITY_WORKSPACE_PERSISTENCE',
);
export const WORKSPACE_AUTHORIZATION = Symbol('WORKSPACE_AUTHORIZATION');
export const OIDC_LOGIN_SERVICE = Symbol('OIDC_LOGIN_SERVICE');
export const OPAQUE_SESSION_SERVICE = Symbol('OPAQUE_SESSION_SERVICE');
export const CSRF_POLICY = Symbol('CSRF_POLICY');
export const SESSION_COOKIE_POLICY = Symbol('SESSION_COOKIE_POLICY');
export const IDENTITY_WORKSPACE_TELEMETRY = Symbol(
  'IDENTITY_WORKSPACE_TELEMETRY',
);
