import {
  HTTP_REQUEST_MANIFEST,
  HTTP_REQUEST_NETWORK_POLICY,
  HTTP_REQUEST_VALUE_POLICY,
  SLACK_SEND_MESSAGE_MANIFEST,
  SLACK_SEND_MESSAGE_POLICY,
  EMAIL_SEND_NOTIFICATION_MANIFEST,
  EMAIL_SEND_NOTIFICATION_POLICY,
} from '@pertexo/integrations';
import { createRegistryReleaseSuccessor } from '@pertexo/node-sdk';
import type { NodeManifest } from '@pertexo/node-sdk';
import {
  CORE_CONDITION_MANIFEST,
  CORE_FOR_EACH_MANIFEST,
  CORE_MERGE_MANIFEST,
  CORE_MERGE_MANIFEST_V2,
  CORE_PARALLEL_MANIFEST,
  CORE_PARALLEL_MANIFEST_V2,
  CORE_REGISTRY_RELEASE_SUPPORT,
  CORE_REGISTRY_RELEASE_SUCCESSOR,
  CORE_SCHEDULE_MANIFEST,
  CORE_SCHEDULE_MANIFEST_V2,
  CORE_SWITCH_MANIFEST,
  CORE_WAIT_MANIFEST,
  CORE_WEBHOOK_MANIFEST,
} from '@pertexo/nodes-core';

type RegistryRelease = Parameters<
  typeof createRegistryReleaseSuccessor
>[0]['previous'];

function stageDefinition(
  previous: RegistryRelease,
  manifest: NodeManifest,
  additionalPolicies: RegistryRelease['policies'] = [],
) {
  const executorAbi = manifest.executorAbi;
  if (executorAbi === undefined)
    throw new Error(
      `${manifest.definition.key} manifest must pin its executor ABI`,
    );
  return createRegistryReleaseSuccessor({
    previous,
    epoch: previous.epoch + 1,
    definitions: [...previous.definitions, manifest],
    executors: [
      ...previous.executors,
      {
        executor: manifest.executor,
        abiVersion: executorAbi,
        definitions: [manifest.definition],
        lifecycle: 'staged' as const,
        policyReferences: manifest.policyReferences,
      },
    ],
    policies: [...previous.policies, ...additionalPolicies],
  });
}

function activateDefinition(previous: RegistryRelease, manifest: NodeManifest) {
  return createRegistryReleaseSuccessor({
    previous,
    epoch: previous.epoch + 1,
    definitions: previous.definitions,
    executors: previous.executors.map((executor) =>
      executor.executor.key === manifest.executor.key &&
      executor.executor.version === manifest.executor.version
        ? { ...executor, lifecycle: 'active' as const }
        : executor,
    ),
    policies: previous.policies,
  });
}

export const PLATFORM_REGISTRY_RELEASE_HTTP_STAGED = stageDefinition(
  CORE_REGISTRY_RELEASE_SUCCESSOR,
  HTTP_REQUEST_MANIFEST,
  [HTTP_REQUEST_NETWORK_POLICY, HTTP_REQUEST_VALUE_POLICY],
);

export const PLATFORM_REGISTRY_RELEASE_HTTP_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_HTTP_STAGED,
  HTTP_REQUEST_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_CONDITION_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_HTTP_ACTIVE,
  CORE_CONDITION_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_CONDITION_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_CONDITION_STAGED,
  CORE_CONDITION_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_SWITCH_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_CONDITION_ACTIVE,
  CORE_SWITCH_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_SWITCH_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_SWITCH_STAGED,
  CORE_SWITCH_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_PARALLEL_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_SWITCH_ACTIVE,
  CORE_PARALLEL_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_PARALLEL_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_PARALLEL_STAGED,
  CORE_PARALLEL_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_MERGE_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_PARALLEL_ACTIVE,
  CORE_MERGE_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_MERGE_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_MERGE_STAGED,
  CORE_MERGE_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_FOR_EACH_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_MERGE_ACTIVE,
  CORE_FOR_EACH_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_FOR_EACH_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_FOR_EACH_STAGED,
  CORE_FOR_EACH_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_WAIT_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_FOR_EACH_ACTIVE,
  CORE_WAIT_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_WAIT_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_WAIT_STAGED,
  CORE_WAIT_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_SLACK_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_WAIT_ACTIVE,
  SLACK_SEND_MESSAGE_MANIFEST,
  [SLACK_SEND_MESSAGE_POLICY],
);

export const PLATFORM_REGISTRY_RELEASE_SLACK_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_SLACK_STAGED,
  SLACK_SEND_MESSAGE_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_EMAIL_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_SLACK_ACTIVE,
  EMAIL_SEND_NOTIFICATION_MANIFEST,
  [EMAIL_SEND_NOTIFICATION_POLICY],
);

export const PLATFORM_REGISTRY_RELEASE_EMAIL_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_EMAIL_STAGED,
  EMAIL_SEND_NOTIFICATION_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_WEBHOOK_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_EMAIL_ACTIVE,
  CORE_WEBHOOK_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_WEBHOOK_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_WEBHOOK_STAGED,
  CORE_WEBHOOK_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_SCHEDULE_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_WEBHOOK_ACTIVE,
  CORE_SCHEDULE_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_SCHEDULE_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_STAGED,
  CORE_SCHEDULE_MANIFEST,
);

export const PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_ACTIVE,
  CORE_SCHEDULE_MANIFEST_V2,
);
export const PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_STAGED,
  CORE_SCHEDULE_MANIFEST_V2,
);
export const PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_ACTIVE,
  CORE_PARALLEL_MANIFEST_V2,
);
export const PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_STAGED,
  CORE_PARALLEL_MANIFEST_V2,
);
export const PLATFORM_REGISTRY_RELEASE_MERGE_V2_STAGED = stageDefinition(
  PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_ACTIVE,
  CORE_MERGE_MANIFEST_V2,
);
export const PLATFORM_REGISTRY_RELEASE_MERGE_V2_ACTIVE = activateDefinition(
  PLATFORM_REGISTRY_RELEASE_MERGE_V2_STAGED,
  CORE_MERGE_MANIFEST_V2,
);

/** Complete audit/test history; never pass this to one serving artifact. */
export const PLATFORM_REGISTRY_RELEASE_HISTORY = Object.freeze([
  ...CORE_REGISTRY_RELEASE_SUPPORT,
  PLATFORM_REGISTRY_RELEASE_HTTP_STAGED,
  PLATFORM_REGISTRY_RELEASE_HTTP_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_CONDITION_STAGED,
  PLATFORM_REGISTRY_RELEASE_CONDITION_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_SWITCH_STAGED,
  PLATFORM_REGISTRY_RELEASE_SWITCH_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_PARALLEL_STAGED,
  PLATFORM_REGISTRY_RELEASE_PARALLEL_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_MERGE_STAGED,
  PLATFORM_REGISTRY_RELEASE_MERGE_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_FOR_EACH_STAGED,
  PLATFORM_REGISTRY_RELEASE_FOR_EACH_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_WAIT_STAGED,
  PLATFORM_REGISTRY_RELEASE_WAIT_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_SLACK_STAGED,
  PLATFORM_REGISTRY_RELEASE_SLACK_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_EMAIL_STAGED,
  PLATFORM_REGISTRY_RELEASE_EMAIL_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_WEBHOOK_STAGED,
  PLATFORM_REGISTRY_RELEASE_WEBHOOK_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_STAGED,
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_STAGED,
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_STAGED,
  PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_MERGE_V2_STAGED,
  PLATFORM_REGISTRY_RELEASE_MERGE_V2_ACTIVE,
]);

/** Backward-compatible default cohort until deployment selects a Phase 4 cohort. */
export const PLATFORM_REGISTRY_RELEASE_SUPPORT = CORE_REGISTRY_RELEASE_SUPPORT;

/** First Phase 4 artifact: current core release plus staged HTTP successor. */
export const PLATFORM_HTTP_STAGING_RELEASE_SUPPORT = Object.freeze([
  CORE_REGISTRY_RELEASE_SUCCESSOR,
  PLATFORM_REGISTRY_RELEASE_HTTP_STAGED,
]);

/** Second Phase 4 artifact: staged predecessor plus active HTTP successor. */
export const PLATFORM_HTTP_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_HTTP_STAGED,
  PLATFORM_REGISTRY_RELEASE_HTTP_ACTIVE,
]);

/** Condition staging artifact: active HTTP predecessor plus staged Condition. */
export const PLATFORM_CONDITION_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_HTTP_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_CONDITION_STAGED,
]);

/** Condition activation artifact: staged predecessor plus active Condition. */
export const PLATFORM_CONDITION_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_CONDITION_STAGED,
  PLATFORM_REGISTRY_RELEASE_CONDITION_ACTIVE,
]);

/** Switch staging artifact: active Condition predecessor plus staged Switch. */
export const PLATFORM_SWITCH_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_CONDITION_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_SWITCH_STAGED,
]);

/** Switch activation artifact: staged predecessor plus active Switch. */
export const PLATFORM_SWITCH_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_SWITCH_STAGED,
  PLATFORM_REGISTRY_RELEASE_SWITCH_ACTIVE,
]);

export const PLATFORM_PARALLEL_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_SWITCH_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_PARALLEL_STAGED,
]);

export const PLATFORM_PARALLEL_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_PARALLEL_STAGED,
  PLATFORM_REGISTRY_RELEASE_PARALLEL_ACTIVE,
]);

export const PLATFORM_MERGE_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_PARALLEL_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_MERGE_STAGED,
]);

export const PLATFORM_MERGE_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_MERGE_STAGED,
  PLATFORM_REGISTRY_RELEASE_MERGE_ACTIVE,
]);

export const PLATFORM_FOR_EACH_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_MERGE_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_FOR_EACH_STAGED,
]);

export const PLATFORM_FOR_EACH_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_FOR_EACH_STAGED,
  PLATFORM_REGISTRY_RELEASE_FOR_EACH_ACTIVE,
]);

export const PLATFORM_WAIT_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_FOR_EACH_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_WAIT_STAGED,
]);
export const PLATFORM_WAIT_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_WAIT_STAGED,
  PLATFORM_REGISTRY_RELEASE_WAIT_ACTIVE,
]);
export const PLATFORM_SLACK_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_WAIT_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_SLACK_STAGED,
]);
export const PLATFORM_SLACK_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_SLACK_STAGED,
  PLATFORM_REGISTRY_RELEASE_SLACK_ACTIVE,
]);
export const PLATFORM_EMAIL_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_SLACK_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_EMAIL_STAGED,
]);
export const PLATFORM_EMAIL_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_EMAIL_STAGED,
  PLATFORM_REGISTRY_RELEASE_EMAIL_ACTIVE,
]);
export const PLATFORM_WEBHOOK_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_EMAIL_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_WEBHOOK_STAGED,
]);
export const PLATFORM_WEBHOOK_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_WEBHOOK_STAGED,
  PLATFORM_REGISTRY_RELEASE_WEBHOOK_ACTIVE,
]);
export const PLATFORM_SCHEDULE_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_WEBHOOK_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_STAGED,
]);
export const PLATFORM_SCHEDULE_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_STAGED,
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_ACTIVE,
]);
export const PLATFORM_SCHEDULE_V2_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_STAGED,
]);
export const PLATFORM_SCHEDULE_V2_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_STAGED,
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_ACTIVE,
]);
export const PLATFORM_PARALLEL_V2_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_STAGED,
]);
export const PLATFORM_PARALLEL_V2_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_STAGED,
  PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_ACTIVE,
]);
export const PLATFORM_MERGE_V2_STAGING_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_ACTIVE,
  PLATFORM_REGISTRY_RELEASE_MERGE_V2_STAGED,
]);
export const PLATFORM_MERGE_V2_ACTIVATION_RELEASE_SUPPORT = Object.freeze([
  PLATFORM_REGISTRY_RELEASE_MERGE_V2_STAGED,
  PLATFORM_REGISTRY_RELEASE_MERGE_V2_ACTIVE,
]);

const platformReleaseCohortConfig = Object.freeze({
  core: Object.freeze({
    support: PLATFORM_REGISTRY_RELEASE_SUPPORT,
    serving: CORE_REGISTRY_RELEASE_SUCCESSOR,
  }),
  http_staging: Object.freeze({
    support: PLATFORM_HTTP_STAGING_RELEASE_SUPPORT,
    serving: CORE_REGISTRY_RELEASE_SUCCESSOR,
  }),
  http_activation: Object.freeze({
    support: PLATFORM_HTTP_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_HTTP_ACTIVE,
  }),
  condition_staging: Object.freeze({
    support: PLATFORM_CONDITION_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_HTTP_ACTIVE,
  }),
  condition_activation: Object.freeze({
    support: PLATFORM_CONDITION_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_CONDITION_ACTIVE,
  }),
  switch_staging: Object.freeze({
    support: PLATFORM_SWITCH_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_CONDITION_ACTIVE,
  }),
  switch_activation: Object.freeze({
    support: PLATFORM_SWITCH_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_SWITCH_ACTIVE,
  }),
  parallel_staging: Object.freeze({
    support: PLATFORM_PARALLEL_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_SWITCH_ACTIVE,
  }),
  parallel_activation: Object.freeze({
    support: PLATFORM_PARALLEL_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_PARALLEL_ACTIVE,
  }),
  merge_staging: Object.freeze({
    support: PLATFORM_MERGE_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_PARALLEL_ACTIVE,
  }),
  merge_activation: Object.freeze({
    support: PLATFORM_MERGE_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_MERGE_ACTIVE,
  }),
  for_each_staging: Object.freeze({
    support: PLATFORM_FOR_EACH_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_MERGE_ACTIVE,
  }),
  for_each_activation: Object.freeze({
    support: PLATFORM_FOR_EACH_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_FOR_EACH_ACTIVE,
  }),
  wait_staging: Object.freeze({
    support: PLATFORM_WAIT_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_FOR_EACH_ACTIVE,
  }),
  wait_activation: Object.freeze({
    support: PLATFORM_WAIT_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_WAIT_ACTIVE,
  }),
  slack_staging: Object.freeze({
    support: PLATFORM_SLACK_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_WAIT_ACTIVE,
  }),
  slack_activation: Object.freeze({
    support: PLATFORM_SLACK_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_SLACK_ACTIVE,
  }),
  email_staging: Object.freeze({
    support: PLATFORM_EMAIL_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_SLACK_ACTIVE,
  }),
  email_activation: Object.freeze({
    support: PLATFORM_EMAIL_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_EMAIL_ACTIVE,
  }),
  webhook_staging: Object.freeze({
    support: PLATFORM_WEBHOOK_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_EMAIL_ACTIVE,
  }),
  webhook_activation: Object.freeze({
    support: PLATFORM_WEBHOOK_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_WEBHOOK_ACTIVE,
  }),
  schedule_staging: Object.freeze({
    support: PLATFORM_SCHEDULE_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_WEBHOOK_ACTIVE,
  }),
  schedule_activation: Object.freeze({
    support: PLATFORM_SCHEDULE_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_SCHEDULE_ACTIVE,
  }),
  schedule_v2_staging: Object.freeze({
    support: PLATFORM_SCHEDULE_V2_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_SCHEDULE_ACTIVE,
  }),
  schedule_v2_activation: Object.freeze({
    support: PLATFORM_SCHEDULE_V2_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_ACTIVE,
  }),
  parallel_v2_staging: Object.freeze({
    support: PLATFORM_PARALLEL_V2_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_SCHEDULE_V2_ACTIVE,
  }),
  parallel_v2_activation: Object.freeze({
    support: PLATFORM_PARALLEL_V2_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_ACTIVE,
  }),
  merge_v2_staging: Object.freeze({
    support: PLATFORM_MERGE_V2_STAGING_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_PARALLEL_V2_ACTIVE,
  }),
  merge_v2_activation: Object.freeze({
    support: PLATFORM_MERGE_V2_ACTIVATION_RELEASE_SUPPORT,
    serving: PLATFORM_REGISTRY_RELEASE_MERGE_V2_ACTIVE,
  }),
});

export type PlatformReleaseCohort = keyof typeof platformReleaseCohortConfig;
export const PLATFORM_RELEASE_COHORTS = Object.freeze(
  Object.keys(platformReleaseCohortConfig) as PlatformReleaseCohort[],
);

export function platformRegistryReleaseSupport(cohort: PlatformReleaseCohort) {
  return platformReleaseCohortConfig[cohort].support;
}

/** Retained immutable releases executable by a cohort, distinct from readiness. */
export function platformExecutableRegistryHistory(
  cohort: PlatformReleaseCohort,
) {
  const maximumEpoch = platformRegistryReleaseSupport(cohort).at(-1)?.epoch;
  if (maximumEpoch === undefined)
    throw new Error('Platform release cohort is empty');
  return Object.freeze(
    PLATFORM_REGISTRY_RELEASE_HISTORY.filter(
      ({ epoch }) => epoch <= maximumEpoch,
    ),
  );
}

/** Release whose executors the cohort's worker actually dispatches. */
export function platformServingRegistryRelease(cohort: PlatformReleaseCohort) {
  return platformReleaseCohortConfig[cohort].serving;
}

export function platformServingReleaseRequiresHttpCapabilities(
  cohort: PlatformReleaseCohort,
): boolean {
  return platformServingRegistryRelease(cohort).executors.some(
    ({ executor, lifecycle }) =>
      executor.key === HTTP_REQUEST_MANIFEST.executor.key &&
      executor.version === HTTP_REQUEST_MANIFEST.executor.version &&
      lifecycle === 'active',
  );
}
