export const IDENTITY_CRYPTO = Symbol('IDENTITY_CRYPTO');
export const IDENTITY_CLOCK = Symbol('IDENTITY_CLOCK');
export const IDENTITY_WORKSPACE_PERSISTENCE = Symbol(
  'IDENTITY_WORKSPACE_PERSISTENCE',
);
export const WORKSPACE_AUTHORIZATION = Symbol('WORKSPACE_AUTHORIZATION');
export const CSRF_POLICY = Symbol('CSRF_POLICY');
export const SESSION_COOKIE_POLICY = Symbol('SESSION_COOKIE_POLICY');
export const SESSION_AUTHORITY = Symbol('SESSION_AUTHORITY');
export const IDENTITY_WORKSPACE_TELEMETRY = Symbol(
  'IDENTITY_WORKSPACE_TELEMETRY',
);
export const INVITATION_TOKEN_PROTECTOR = Symbol('INVITATION_TOKEN_PROTECTOR');
export const INVITATION_ALLOWED_ORIGIN = Symbol('INVITATION_ALLOWED_ORIGIN');
